"""codetoy._input — mouse, keyboard, and touch input"""

def mouseX() -> float: ...
def mouseY() -> float: ...
def isMouseDown(button: int) -> bool: ...
def isKeyDown(key: str) -> bool: ...
def touchCount() -> int: ...
def isTouchDown(id: int = -1) -> bool: ...
def touchX(id: int) -> float: ...
def touchY(id: int) -> float: ...
