"""codetoy.canvas — 2D drawing API"""

def reset() -> None: ...
def push() -> None: ...
def pop() -> None: ...

def noFill() -> None: ...
def noStroke() -> None: ...
def fill(r: float, g: float, b: float, a: float = 1.0) -> None: ...
def fillStyle(color: str) -> None: ...
def stroke(r: float, g: float, b: float, a: float = 1.0) -> None: ...
def strokeStyle(color: str) -> None: ...

def lineWidth(width: float) -> None: ...
def lineJoin(joinStyle: str) -> None: ...
def lineCap(capStyle: str) -> None: ...
def lineMiterLimit(limit: float) -> None: ...

def rect(x: float, y: float, width: float, height: float, r: float = 0.0) -> None: ...
def circle(x: float, y: float, radius: float) -> None: ...
def line(x1: float, y1: float, x2: float, y2: float) -> None: ...
def arc(x: float, y: float, radius: float, startAngle: float, endAngle: float, anticlockwise: bool = False) -> None: ...
def ellipse(x: float, y: float, w: float, h: float) -> None: ...
def triangle(x1: float, y1: float, x2: float, y2: float, x3: float, y3: float) -> None: ...
def polygon(pts: list) -> None: ...

def scale(x: float, y: float) -> None: ...
def rotate(radians: float) -> None: ...
def translate(x: float, y: float) -> None: ...
def resetTransform() -> None: ...

def beginPath() -> None: ...
def closePath() -> None: ...
def fillPath() -> None: ...
def strokePath() -> None: ...
def moveTo(x: float, y: float) -> None: ...
def lineTo(x: float, y: float) -> None: ...
def bezierCurveTo(cp1x: float, cp1y: float, cp2x: float, cp2y: float, x: float, y: float) -> None: ...
def quadraticCurveTo(cpx: float, cpy: float, x: float, y: float) -> None: ...

def font(family: str, size: float, weight: str = "normal") -> None: ...
def text(content: str, x: float, y: float) -> None: ...
def measureText(content: str) -> float: ...
