"""codetoy.screen — canvas dimensions and frame info"""

def width() -> float: ...
def height() -> float: ...
def centerX() -> float: ...
def centerY() -> float: ...
def frameCount() -> int: ...
def fps() -> float: ...
